services:
  postgres:
    image: postgres:16
    container_name: sistema-barbearia-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: barbearia
      POSTGRES_PASSWORD: barbearia123
      POSTGRES_DB: sistema_barbearia
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  